{% set name = "pyinstaller-hooks-contrib" %}
{% set version = "2024.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/v{{ version }}.tar.gz
  sha256: 6bc703891fe21e8b983483a87b1a21a2ec6d3329575a6955457e639449efe78b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: True  # [py<37]
  entry_points:
    - hook-dirs = _pyinstaller_hooks_contrib.hooks:get_hook_dirs
    - tests = _pyinstaller_hooks_contrib.tests:get_test_dirs

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - setuptools >=42.0.0
    - importlib_metadata >=4.6  # [py<310]
    - packaging >=22.0

test:
  source_files:
    - src/_pyinstaller_hooks_contrib/tests
    - src/_pyinstaller_hooks_contrib/tests/scripts
    - src/_pyinstaller_hooks_contrib/tests/data/test_hydra
  imports:
    - _pyinstaller_hooks_contrib
  requires:
    - pip
    - pytest >=2.7.3
    - pytest-timeout
    - pytest-xdist
    - execnet >=1.5.0
    - psutil
    - pyinstaller
  commands:
    - pip check
    - pytest src/_pyinstaller_hooks_contrib/tests/test_libraries.py -v

about:
  home: https://github.com/pyinstaller/pyinstaller-hooks-contrib
  summary: Community maintained hooks for PyInstaller
  license: Apache-2.0 OR GPL-2.0-or-later
  license_family: Other
  license_file:
    - LICENSE.GPL.txt
    - LICENSE.APL.txt
  description: |
    A "hook" file extends PyInstaller to adapt it to the special needs and
    methods used by a Python package. The word "hook" is used for two kinds of
    files. A runtime hook helps the bootloader to launch an app, setting up the
    environment. A package hook (there are several types of those) tells
    PyInstaller what to include in the final app - such as the data files and
    (hidden) imports mentioned above.
  doc_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/README.md
  dev_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib

extra:
  skip-lints:
    - python_build_tool_in_run
  recipe-maintainers:
    - nehaljwani
