{% set name = "pyinstaller-hooks-contrib" %}
{% set version = "2024.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/v{{ version }}.tar.gz
  sha256: fd5f37dcf99bece184e40642af88be16a9b89613ecb958a8bd1136634fc9fac5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: True  # [py<37]
  entry_points:
    - hook-dirs = _pyinstaller_hooks_contrib.hooks:get_hook_dirs
    - tests = _pyinstaller_hooks_contrib.tests:get_test_dirs

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - _pyinstaller_hooks_contrib
    - _pyinstaller_hooks_contrib.hooks
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyinstaller/pyinstaller-hooks-contrib
  summary: Community maintained hooks for PyInstaller
  license: Apache-2.0 OR GPL-2.0-or-later
  license_family: Other
  license_file:
    - LICENSE.GPL.txt
    - LICENSE.APL.txt
  description: |
    A "hook" file extends PyInstaller to adapt it to the special needs and
    methods used by a Python package. The word "hook" is used for two kinds of
    files. A runtime hook helps the bootloader to launch an app, setting up the
    environment. A package hook (there are several types of those) tells
    PyInstaller what to include in the final app - such as the data files and
    (hidden) imports mentioned above.
  doc_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/README.md
  dev_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib

extra:
  recipe-maintainers:
    - nehaljwani
